name: CI pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Set up Node.js
        uses: action/setup-node@v3
      - name: Install dependancy
        run: npm run install
      - name: Run tests
        run: npm run test
